name: practices
description: A new Dart project
environment:
  sdk: '>=3.3.0 <4.0.0'  # Ensure this is 3.3 or higher

dependencies:
  test_package:
    path: test_package
  http: ^1.3.0
  intl: ^0.18.1
